### ISSUE TITLE
Upgrading tests to Moq 4.7 causes runtime errors

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/Routing#390]
**Repro**
Change `<MoqVersion>` in dependencies.props to 4.7.1.
Run tests

**Error**
```
Interface not found.
Stack Trace:
at System.RuntimeTypeHandle.VerifyInterfaceIsImplemented(Runtime
TypeHandle handle, RuntimeTypeHandle interfaceHandle)
at System.RuntimeType.GetInterfaceMap(Type ifaceType)
at Moq.Extensions.IsGetObjectDataVirtual(Type typeToMock)
at Moq.Extensions.IsSerializableMockable(Type typeToMock)
at Moq.SerializableTypesValueProvider.ProvideDefault(MethodInfo member)
```

**Comment by kichalla** [comment]
This happens only for net46 tfm and to repro, just do `var httpContext = Mock.Of<HttpContext>();`

**Comment by kichalla** [comment]
Filed: https://github.com/moq/moq4/issues/340
cc @pranavkm

**Comment by kichalla** [comment]
2388cca5ac7e8ab83f4c7b46145c90e9966403a7
