### ISSUE TITLE
ArgumentException: An element with the key '(key)' already exists in the RouteValueDictionary.

### ISSUE THREAD

**Issue by timmydo** [aspnet/Routing#394]
Hello, I'm trying to use attribute routing and either things are broken or I'm not getting it. Here is a sample controller

```
namespace WebApplication1.Controllers
{
    [Route("/api")]
    public class TestController : Controller
    {
        [HttpPost("environment('{environment:alpha}')/copy('{newEnvironment:alpha}')")]
        public bool Clone([FromRoute(Name = "environment")]string env, [FromRoute(Name = "newEnvironment")] string env2)
        {
            return true;
        }


        [HttpGet("environment('{environment:alpha}')/promotions('{name:alpha}')")]
        public bool GetPromotion([FromRoute(Name = "environment")] string env, [FromRoute(Name = "name")] string name)
        {
            return true;
        }
    }
}
```

If I make a request to any endpoint, I see this error:
```
System.ArgumentException: An element with the key 'environment' already exists in the RouteValueDictionary.
Parameter name: key
   at Microsoft.AspNetCore.Routing.RouteValueDictionary.Add(String key, Object value)
   at Microsoft.AspNetCore.Routing.Template.TemplateMatcher.MatchComplexSegmentCore(TemplateSegment routeSegment, String requestSegment, IReadOnlyDictionary`2 defaults, RouteValueDictionary values, Int32 indexOfLastSegmentUsed)
   at Microsoft.AspNetCore.Routing.Template.TemplateMatcher.MatchComplexSegment(TemplateSegment routeSegment, String requestSegment, IReadOnlyDictionary`2 defaults, RouteValueDictionary values)
   at Microsoft.AspNetCore.Routing.Template.TemplateMatcher.TryMatch(PathString path, RouteValueDictionary values)
   at Microsoft.AspNetCore.Routing.Tree.TreeRouter.<RouteAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Routing.RouteCollection.<RouteAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
```

**Comment by timmydo** [comment]
@rynowak

**Comment by rynowak** [comment]
What version is this on? We addressed a similar bug here https://github.com/aspnet/Routing/issues/370

**Comment by timmydo** [comment]
aspnetcore.mvc 1.1.1

**Comment by rynowak** [comment]
@Eilon - we should investigate this. If there's an issue here it's a potential path candidate.

**Comment by Eilon** [comment]
@SteveSandersonMS can you investigate, and also see if perhaps there's a workaround for this?

**Comment by SteveSandersonMS** [comment]
@timmydo thanks for reporting this! Confirmed as a bug, with fix submitted as PR #395.

As a workaround, you could use different parameter names in your route entries, e.g.,

```csharp
namespace WebApplication1.Controllers
{
    [Route("/api")]
    public class TestController : Controller
    {
        [HttpPost("environment('{cloneenvironment:alpha}')/copy('{newEnvironment:alpha}')")]
        public bool Clone([FromRoute(Name = "cloneenvironment")]string env, [FromRoute(Name = "newEnvironment")] string env2)
        {
            return true;
        }


        [HttpGet("environment('{promotionsenvironment:alpha}')/promotions('{name:alpha}')")]
        public bool GetPromotion([FromRoute(Name = "promotionsenvironment")] string env, [FromRoute(Name = "name")] string name)
        {
            return true;
        }
    }
}
```

i.e., as a temporary workaround, don't use the same key name `environment` for both. Sorry for the inconvenience!

**Comment by timmydo** [comment]
Thanks.

**Comment by Eilon** [comment]
@SteveSandersonMS  - `3 - Done`? 😄
