### ISSUE TITLE
Tests with non-MatcherEndpoint

### ISSUE THREAD

**Issue by JamesNK** [aspnet/Routing#648]
See https://github.com/aspnet/Routing/pull/646#discussion_r204257353

Make sure that new functionality works with non-MatcherEndpoints as expected.

**Comment by rynowak** [comment]
Note that how this is shaping up, we'll have `Endpoint` and `RouteEndpoint`. We ascribe 'routing' semantics to `RouteEndpoint` and 'execution' semantics to `Endpoint`.

I think it would be enough for this work item to change `HttpMethodMatcherPolicy` to use `Endpoint` instead of `RouteEndpoint`. We already have tests that we don't inject non-RouteEndpoint types into the routing system, and this is the one other place it can happen. We don't really have places in the code that I can find where we downcast and it isn't intended.

**Comment by JamesNK** [comment]
I recall my main concern was non-MatcherEndpoints being passed to the matcher. The casting going on inside matching made me nervious. I want to ensure that the DFA matcher doesn't let non-MatcherEndpoints slip through and throw InvalidCastExceptions.

**Comment by rynowak** [comment]
Ah yes, I found it. https://github.com/aspnet/Routing/blob/release/2.2/src/Microsoft.AspNetCore.Routing/Matching/DfaMatcherBuilder.cs#L550 This is the one.

**Comment by JamesNK** [comment]
Ka-boom
```
System.InvalidCastException: Unable to cast object of type &#x27;Microsoft.AspNetCore.Http.Endpoint&#x27; to type &#x27;Microsoft.AspNetCore.Routing.RouteEndpoint&#x27;.
   at System.Linq.Enumerable.CastIterator[TResult](IEnumerable source)&#x2B;MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Microsoft.AspNetCore.Routing.Matching.DfaMatcherBuilder.ApplyPolicies(DfaNode node) in /_/src/Microsoft.AspNetCore.Routing/Matching/DfaMatcherBuilder.cs:line 547
   at Microsoft.AspNetCore.Routing.Matching.DfaNode.Visit(Action`1 visitor) in /_/src/Microsoft.AspNetCore.Routing/Matching/DfaNode.cs:line 69
   at Microsoft.AspNetCore.Routing.Matching.DfaNode.Visit(Action`1 visitor) in /_/src/Microsoft.AspNetCore.Routing/Matching/DfaNode.cs:line 46
   at Microsoft.AspNetCore.Routing.Matching.DfaNode.Visit(Action`1 visitor) in /_/src/Microsoft.AspNetCore.Routing/Matching/DfaNode.cs:line 46
   at Microsoft.AspNetCore.Routing.Matching.DfaMatcherBuilder.BuildDfaTree() in /_/src/Microsoft.AspNetCore.Routing/Matching/DfaMatcherBuilder.cs:line 192
   at Microsoft.AspNetCore.Routing.Matching.DfaMatcherBuilder.Build() in /_/src/Microsoft.AspNetCore.Routing/Matching/DfaMatcherBuilder.cs:line 218
   at Microsoft.AspNetCore.Routing.Matching.DataSourceDependentMatcher.CreateMatcher(IReadOnlyList`1 endpoints) in /_/src/Microsoft.AspNetCore.Routing/Matching/DataSourceDependentMatcher.cs:line 49
   at Microsoft.AspNetCore.Routing.DataSourceDependentCache`1.Initialize() in /_/src/Microsoft.AspNetCore.Routing/DataSourceDependentCache.cs:line 51
   at System.Threading.LazyInitializer.EnsureInitializedCore[T](T&amp; target, Boolean&amp; initialized, Object&amp; syncLock, Func`1 valueFactory)
   at Microsoft.AspNetCore.Routing.Matching.DataSourceDependentMatcher..ctor(EndpointDataSource dataSource, Func`1 matcherBuilderFactory) in /_/src/Microsoft.AspNetCore.Routing/Matching/DataSourceDependentMatcher.cs:line 25
   at Microsoft.AspNetCore.Routing.Matching.DfaMatcherFactory.CreateMatcher(EndpointDataSource dataSource) in /_/src/Microsoft.AspNetCore.Routing/Matching/DfaMatcherFactory.cs:line 32
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.InitializeAsync() in /_/src/Microsoft.AspNetCore.Routing/EndpointRoutingMiddleware.cs:line 112
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext) in /_/src/Microsoft.AspNetCore.Routing/EndpointRoutingMiddleware.cs:line 61
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

**Comment by JamesNK** [comment]
To repo change the endpoint returned from `ConsumesMatcherPolicy.CreateRejectionEndpoint` from `RouteEndpoint` to `Endpoint`.
```
Test Name:	Microsoft.AspNetCore.Mvc.FunctionalTests.ConsumesAttributeEndpointRoutingTests.DerivedClassLevelAttribute_OveridesBaseClassLevel
Test FullName:	Microsoft.AspNetCore.Mvc.FunctionalTests.ConsumesAttributeEndpointRoutingTests.DerivedClassLevelAttribute_OveridesBaseClassLevel
Test Source:	C:\Development\Source\Mvc\test\Microsoft.AspNetCore.Mvc.FunctionalTests\ConsumesAttributeTestsBase.cs : line 110
Test Outcome:	Failed
Test Duration:	0:00:25.373

Result StackTrace:	
at System.Linq.Enumerable.CastIterator[TResult](IEnumerable source)+MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Microsoft.AspNetCore.Routing.Matching.DfaMatcherBuilder.ApplyPolicies(DfaNode node) in /_/src/Microsoft.AspNetCore.Routing/Matching/DfaMatcherBuilder.cs:line 547
   at Microsoft.AspNetCore.Routing.Matching.DfaNode.Visit(Action`1 visitor) in /_/src/Microsoft.AspNetCore.Routing/Matching/DfaNode.cs:line 69
   at Microsoft.AspNetCore.Routing.Matching.DfaNode.Visit(Action`1 visitor) in /_/src/Microsoft.AspNetCore.Routing/Matching/DfaNode.cs:line 46
   at Microsoft.AspNetCore.Routing.Matching.DfaNode.Visit(Action`1 visitor) in /_/src/Microsoft.AspNetCore.Routing/Matching/DfaNode.cs:line 46
   at Microsoft.AspNetCore.Routing.Matching.DfaMatcherBuilder.BuildDfaTree() in /_/src/Microsoft.AspNetCore.Routing/Matching/DfaMatcherBuilder.cs:line 192
   at Microsoft.AspNetCore.Routing.Matching.DfaMatcherBuilder.Build() in /_/src/Microsoft.AspNetCore.Routing/Matching/DfaMatcherBuilder.cs:line 218
   at Microsoft.AspNetCore.Routing.Matching.DataSourceDependentMatcher.CreateMatcher(IReadOnlyList`1 endpoints) in /_/src/Microsoft.AspNetCore.Routing/Matching/DataSourceDependentMatcher.cs:line 49
   at Microsoft.AspNetCore.Routing.DataSourceDependentCache`1.Initialize() in /_/src/Microsoft.AspNetCore.Routing/DataSourceDependentCache.cs:line 51
   at System.Threading.LazyInitializer.EnsureInitializedCore[T](T& target, Boolean& initialized, Object& syncLock, Func`1 valueFactory)
   at Microsoft.AspNetCore.Routing.Matching.DataSourceDependentMatcher..ctor(EndpointDataSource dataSource, Func`1 matcherBuilderFactory) in /_/src/Microsoft.AspNetCore.Routing/Matching/DataSourceDependentMatcher.cs:line 25
   at Microsoft.AspNetCore.Routing.Matching.DfaMatcherFactory.CreateMatcher(EndpointDataSource dataSource) in /_/src/Microsoft.AspNetCore.Routing/Matching/DfaMatcherFactory.cs:line 32
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.InitializeAsync() in /_/src/Microsoft.AspNetCore.Routing/EndpointRoutingMiddleware.cs:line 112
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext) in /_/src/Microsoft.AspNetCore.Routing/EndpointRoutingMiddleware.cs:line 61
   at Microsoft.AspNetCore.Mvc.FunctionalTests.CultureReplacerMiddleware.Invoke(HttpContext context) in C:\Development\Source\Mvc\test\Microsoft.AspNetCore.Mvc.FunctionalTests\Infrastructure\CultureReplacerMiddleware.cs:line 45
   at Microsoft.AspNetCore.TestHost.HttpContextBuilder.<>c__DisplayClass10_0.<<SendAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.TestHost.ClientHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Microsoft.AspNetCore.Mvc.FunctionalTests.ConsumesAttributeTestsBase`1.DerivedClassLevelAttribute_OveridesBaseClassLevel() in C:\Development\Source\Mvc\test\Microsoft.AspNetCore.Mvc.FunctionalTests\ConsumesAttributeTestsBase.cs:line 123
--- End of stack trace from previous location where exception was thrown ---
Result Message:	System.InvalidCastException : Unable to cast object of type 'Microsoft.AspNetCore.Http.Endpoint' to type 'Microsoft.AspNetCore.Routing.RouteEndpoint'.
```
