### ISSUE TITLE
Decision Tree can throw when ambient values = null

### ISSUE THREAD

**Issue by rynowak** [aspnet/Routing#810]
You get a call stack like: 

```
at Microsoft.AspNetCore.Routing.Internal.LinkGenerationDecisionTree.Walk(List`1 results, RouteValueDictionary values, RouteValueDictionary ambientValues, DecisionTreeNode`1 node, Boolean isFallbackPath)
   at Microsoft.AspNetCore.Routing.Internal.LinkGenerationDecisionTree.GetMatches(RouteValueDictionary values, RouteValueDictionary ambientValues)
   at Microsoft.AspNetCore.Routing.RouteValuesBasedEndpointFinder.FindEndpoints(RouteValuesAddress address)
   at Microsoft.AspNetCore.Routing.DefaultLinkGenerator.GetEndpoints[TAddress](TAddress address)
   at Microsoft.AspNetCore.Routing.DefaultLinkGenerator.GetUriByAddress[TAddress](HttpContext httpContext, TAddress address, RouteValueDictionary values, RouteValueDictionary ambientValues, String scheme, Nullable`1 host, Nullable`1 pathBase, FragmentString fragment, LinkOptions options)
   at Microsoft.AspNetCore.Routing.ControllerLinkGeneratorExtensions.GetUriByAction(LinkGenerator generator, HttpContext httpContext, String action, String controller, Object values, String scheme, Nullable`1 host, Nullable`1 pathBase, FragmentString fragment, LinkOptions options) in C:\git\aspnet\Mvc\src\Microsoft.AspNetCore.Mvc.Core\Routing\ControllerLinkGeneratorExtensions.cs:line 168
   at Microsoft.AspNetCore.Routing.LinkGeneratorRouteValuesAddressExtensionsTest.GetUriByAction_WithHttpContext_WithPathBaseAndFragment() in C:\git\aspnet\Mvc\test\Microsoft.AspNetCore.Mvc.Core.Test\Routing\ControllerLinkGeneratorExtensionsTest.cs:line 168
Result Message:	System.NullReferenceException : Object reference not set to an instance of an object.
```

The world is already a pretty harsh place, we should try to be more accepting of others, regardless of whether they have ambient values.

**Comment by rynowak** [comment]
There will be a workaround to remove from MVC - search for this issue #

**Comment by rynowak** [comment]
Leaving this open until the workaround is removed everywhere as a reminder.

**Comment by rynowak** [comment]
Closing this since the packages were already updated in MVC, there's nothing to remove 😁
